//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media()
        {
            this.Deleted = false;
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string Format { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Event { get; set; }
        public string People { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string Location { get; set; }
        public bool Deleted { get; set; }
    }
}
